name 'chef_personal'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures chef_personal'
long_description 'Installs/Configures chef_personal'
version '0.1.0'
